/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GolferId = IDL.Principal;
export const CallawayResult = IDL.Record({
  'net' : IDL.Int,
  'adjustment' : IDL.Int,
  'deduction' : IDL.Nat,
  'gross' : IDL.Nat,
});
export const EventResult = IDL.Record({
  'results' : IDL.Vec(IDL.Tuple(GolferId, CallawayResult)),
  'coursePar' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getLatestResult' : IDL.Func([], [IDL.Opt(EventResult)], ['query']),
  'submitEvent' : IDL.Func([GolferId, IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
  'updateEvent' : IDL.Func([GolferId, IDL.Vec(IDL.Nat)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GolferId = IDL.Principal;
  const CallawayResult = IDL.Record({
    'net' : IDL.Int,
    'adjustment' : IDL.Int,
    'deduction' : IDL.Nat,
    'gross' : IDL.Nat,
  });
  const EventResult = IDL.Record({
    'results' : IDL.Vec(IDL.Tuple(GolferId, CallawayResult)),
    'coursePar' : IDL.Nat,
  });
  
  return IDL.Service({
    'getLatestResult' : IDL.Func([], [IDL.Opt(EventResult)], ['query']),
    'submitEvent' : IDL.Func([GolferId, IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
    'updateEvent' : IDL.Func([GolferId, IDL.Vec(IDL.Nat)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };